### ISSUE TITLE
generate_point_forecasts can make unrealistic week point values

### ISSUE THREAD

**Issue by craigjmcgowan** [jarad/FluSight#15]
`generate_point_forecasts` uses the expected value to create the point values. However, with onset week and peak week, this can result in point values in the 20s due to probabilities in weeks 1-5 and weeks 48-52 both affecting the result. 

One way to get around this would be to simply add 52 to all new year weeks at the beginning of the function and then adjust the point value at the end if >52 - I've used this approach in other functions and it works to keep the weeks in the proper order.

**Comment by jarad** [comment]
Good call. In our own work, we set MMWRweek 35 to be our week 1. Your solution is a good one.
