### ISSUE TITLE
generate_point_forecast relies on column names that are different from the template

### ISSUE THREAD

**Issue by nickreich** [jarad/FluSight#17]
I was trying to use this function, but while the template lists column names as (notice the upper case):
Location,Target,Type,Unit,Bin_start_incl,Bin_end_notincl,Value

This function seems to want lower-case column names, which would violate template standards.

**Comment by craigjmcgowan** [comment]
That's a good point. I believe most of the other functions do as well - in the `read_entry` file we set all the column names to lower case at the beginning but don't do it for any other functions. Perhaps the easiest way to deal with this would be to set column names to lower case at the beginning of any function that reads in an entry. Then at the end we could rename the columns to match the template exactly. 

Not the most efficient but I think it should work....and next year perhaps we just make the column names lowercase. I know from talking with Juan that the website backend will be converting all the column names to lowercase anyway.

**Comment by craigjmcgowan** [comment]
Hmmm, this is going to involve redoing all of the stored datasets too if we rename the columns at the end of the function. 

Do we think it's worth re-naming the columns in the output, given that the analytics on our end are case-insensitive with regards to the column names?

**Comment by nickreich** [comment]
No, probably not worth changing. But if you guys don't care about the 
cases of the column names, you should maybe let folks know.

## 

Nicholas G. Reich, Ph.D.
Assistant Professor
Department of Biostatistics and Epidemiology
School of Public Health and Health Sciences
University of Massachusetts, Amherst

413.545.4534
nick@schoolph.umass.edu
http://reichlab.github.io/
on twitter: @reichlab

**Comment by craigjmcgowan** [comment]
Sounds good - I will send that email and also add `tolower()` to the other functions to ensure everything runs smoothly.
