### ISSUE TITLE
verify_colnames fails with error

### ISSUE THREAD

**Issue by elray1** [jarad/FluSight#21]
"Error in colnames(full_entry_score) : object 'full_entry_score' not found"

This was called via:
5: colnames(full_entry_score)
4: verify_colnames(entry, challenge)
3: arrange_entry(entry = entry, challenge = challenge)
2: read_entry(file, challenge)
1: FluSight::verify_entry_file(res_file)

Using the version of FluSight available to be installed from GitHub on 10/1/2017.

**Comment by craigjmcgowan** [comment]
Thanks Evan. I'm traveling tomorrow and will take a look on the plane...
