### ISSUE TITLE
Allow entries with only national forecasts

### ISSUE THREAD

**Issue by jarad** [jarad/FluSight#6]
The guidelines state

> Forecasts must be provided at the national level. Forecasts at the HHS region level are also encouraged.

thus we should allow entries that only have national forecasts, but currently we are requiring all forecasts.

**Comment by craigjmcgowan** [comment]
That's a good point that I forgot about since all teams submitted regional forecasts this year. I can take a look this afternoon - we still need to make sure those forecasts are valid if they are submitted.

**Comment by jarad** [comment]
I believe the code does this. At least the new data.frame [minimal_entry](https://github.com/jarad/FluSight/blob/master/data/minimal_entry.rda) which only includes the national forecasts passes the verification tests.
